name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_COMMIT_TOKEN: ${{ secrets.COMMITER_PAT }}
          USERNAME: ${{ github.repository_owner }}
          SETTINGS: "profile-3d-contrib/settings.json"
      - name: Commit & Push
        run: |
          echo "machine github.com" > ~/.netrc
          echo "login your_username" >> ~/.netrc
          echo "password $GITHUB_COMMIT_TOKEN" >> ~/.netrc
          chmod 600 ~/.netrc
          git config --global credential.helper 'cache --timeout=120'
          git config user.name ayer-ribeiro
          git config user.email ayerrsn2@gmail.com
          git remote -v
          git add -A .
          git commit -m "update 3D profile contrib image"
          git push
          rm ~/.netrc
